setwd("~/Downloads")
electric<-read.table("household_power_consumption.txt",sep=";",header=T,na.strings="?")
electric$Date<-as.Date(electric$Date,format="%d/%m/%Y")
electric.sub<-electric[electric$Date<=as.Date("2007-02-02")&electric$Date>=as.Date("2007-02-01"),]
electric.sub$DateTime<-as.POSIXct(paste(electric.sub$Date,electric.sub$Time),format="%Y-%m-%d %H:%M:%S")
electric.sub$Sub_metering_1<-as.numeric(electric.sub$Sub_metering_1)
electric.sub$Sub_metering_2<-as.numeric(electric.sub$Sub_metering_2)
electric.sub$Sub_metering_3<-as.numeric(electric.sub$Sub_metering_3)
plot(electric.sub$DateTime,electric.sub$Sub_metering_1,xlab="",ylab="Energy Sub Metering",main="",type="l",lwd=2,col="black",ylim=c(0,34))
lines(electric.sub$DateTime,electric.sub$Sub_metering_2,type="l",lwd=2,col="red")
lines(electric.sub$DateTime,electric.sub$Sub_metering_3,type="l",lwd=2,col="blue")
legend(max(electric.sub$DateTime)-40000,36,c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1,cex=0.5)
dev.copy(png,'rplot3.png')
dev.off()
