setwd("~/Downloads")
electric<-read.table("household_power_consumption.txt",sep=";",header=T,na.strings="?")
electric$Date<-as.Date(electric$Date,format="%d/%m/%Y")
electric.sub<-electric[electric$Date<=as.Date("2007-02-02")&electric$Date>=as.Date("2007-02-01"),]
electric.sub$DateTime<-as.POSIXct(paste(electric.sub$Date,electric.sub$Time),format="%Y-%m-%d %H:%M:%S")
electric.sub$Sub_metering_1<-as.numeric(electric.sub$Sub_metering_1)
electric.sub$Sub_metering_2<-as.numeric(electric.sub$Sub_metering_2)
electric.sub$Sub_metering_3<-as.numeric(electric.sub$Sub_metering_3)
par(mfrow=c(2,2))
plot(electric.sub$DateTime,electric.sub$Global_active_power,xlab="datetime",ylab="Global Active Power (kilowatts)",main="",type="l",lwd=2)
plot(electric.sub$DateTime,electric.sub$Voltage,xlab="",ylab="Voltage",main="",type="l",lwd=2)
plot(electric.sub$DateTime,electric.sub$Sub_metering_1,xlab="",ylab="Energy Sub Metering",main="",type="l",lwd=2,col="black",ylim=c(0,34))
lines(electric.sub$DateTime,electric.sub$Sub_metering_2,type="l",lwd=2,col="red")
lines(electric.sub$DateTime,electric.sub$Sub_metering_3,type="l",lwd=2,col="blue")
legend(max(electric.sub$DateTime)-72000,37.5,rep("",3),col=c("black","red","blue"),lwd=3,cex=0.3,bty="n")
text(rep(max(electric.sub$DateTime)-20000,3),c(26,30,34),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col="black",lwd=1)
plot(electric.sub$DateTime,electric.sub$Global_active_power,xlab="datetime",ylab="Global_reactive_power",main="",type="l",lwd=2)
dev.copy(png,'rplot4.png')
dev.off()
